- name: Configuring the DB
  hosts: db 
  become: yes
  vars:
    login_host: db
  tasks:
  - name: Installing MySQL
    ansible.builtin.dnf:
      name: mysql-server
      state: latest # or latest

  - name: start and enable the mysql-server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
# check password is already setup or not
  - name: check DB Connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{login_host}}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output
  
  - name: print output
    ansible.builtin.debug:
      msg: "output: {{mysql_connection_output}}"

      
