- name: Configuring the frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: Installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: start and Enable the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: delete the default content
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent
  